name: 🚀 Deploy Static Website to S3

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to main

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy to S3
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🧰 Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: 🚀 Sync files to S3 bucket
        run: |
          aws s3 sync . s3://devops-project-scalable-static-site \
            --delete \
            --cache-control "no-cache, no-store, must-revalidate" \
            --exclude ".git/*" \
            --exclude ".github/*" \
            --exclude "README.md"

      - name: ✅ List uploaded files (for logging)
        run: aws s3 ls s3://devops-project-scalable-static-site --recursive

